//! Expense DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Expense;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::ExpenseApprovalState;
use crate::domain::entity::ExpensePaymentMode;
use crate::domain::entity::ExpenseState;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Expense
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateExpenseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "category_id")]
    pub category_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "expense_date")]
    pub expense_date: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub description: String,
    #[serde(alias = "amount_total")]
    pub amount_total: Decimal,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    #[serde(alias = "payment_mode")]
    pub payment_mode: ExpensePaymentMode,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reference: Option<String>,
    #[serde(alias = "approval_state")]
    pub approval_state: ExpenseApprovalState,
    pub state: ExpenseState,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "approval_request_id")]
    pub approval_request_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "journal_id")]
    pub journal_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "accounting_post_id")]
    pub accounting_post_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "reimbursement_id")]
    pub reimbursement_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "receipt_file_id")]
    pub receipt_file_id: Option<Uuid>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Expense
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateExpenseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "category_id")]
    pub category_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "expense_date")]
    pub expense_date: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub description: String,
    #[serde(alias = "amount_total")]
    pub amount_total: Decimal,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    #[serde(alias = "payment_mode")]
    pub payment_mode: ExpensePaymentMode,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reference: Option<String>,
    #[serde(alias = "approval_state")]
    pub approval_state: ExpenseApprovalState,
    pub state: ExpenseState,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "approval_request_id")]
    pub approval_request_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "journal_id")]
    pub journal_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "accounting_post_id")]
    pub accounting_post_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "reimbursement_id")]
    pub reimbursement_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "receipt_file_id")]
    pub receipt_file_id: Option<Uuid>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Expense
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchExpenseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "category_id")]
    pub category_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "expense_date")]
    pub expense_date: Option<NaiveDate>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "amount_total")]
    pub amount_total: Option<Decimal>,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "payment_mode")]
    pub payment_mode: Option<ExpensePaymentMode>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reference: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "approval_state")]
    pub approval_state: Option<ExpenseApprovalState>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub state: Option<ExpenseState>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "approval_request_id")]
    pub approval_request_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "journal_id")]
    pub journal_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "accounting_post_id")]
    pub accounting_post_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "reimbursement_id")]
    pub reimbursement_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "receipt_file_id")]
    pub receipt_file_id: Option<Uuid>,
}

impl PatchExpenseDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.category_id.is_some() || self.expense_date.is_some() || self.description.is_some() || self.amount_total.is_some() || self.currency.is_some() || self.payment_mode.is_some() || self.reference.is_some() || self.approval_state.is_some() || self.state.is_some() || self.approval_request_id.is_some() || self.journal_id.is_some() || self.accounting_post_id.is_some() || self.reimbursement_id.is_some() || self.receipt_file_id.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Expense entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ExpenseResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub category_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub expense_date: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub description: String,
    pub amount_total: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub payment_mode: ExpensePaymentMode,
    pub reference: Option<String>,
    pub approval_state: ExpenseApprovalState,
    pub state: ExpenseState,
    pub approval_request_id: Option<Uuid>,
    pub journal_id: Option<Uuid>,
    pub accounting_post_id: Option<Uuid>,
    pub reimbursement_id: Option<Uuid>,
    pub receipt_file_id: Option<Uuid>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Expense entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ExpenseListResponseDto {
    /// List of items
    pub items: Vec<ExpenseResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl ExpenseListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<ExpenseResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ExpenseSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub category_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Expense> for ExpenseResponseDto {
    fn from(entity: Expense) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            category_id: entity.category_id,
            expense_date: entity.expense_date,
            description: entity.description,
            amount_total: entity.amount_total,
            currency: entity.currency,
            payment_mode: entity.payment_mode,
            reference: entity.reference,
            approval_state: entity.approval_state,
            state: entity.state,
            approval_request_id: entity.approval_request_id,
            journal_id: entity.journal_id,
            accounting_post_id: entity.accounting_post_id,
            reimbursement_id: entity.reimbursement_id,
            receipt_file_id: entity.receipt_file_id,
            metadata: entity.metadata,
        }
    }
}

impl From<Expense> for ExpenseSummaryDto {
    fn from(entity: Expense) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            category_id: entity.category_id,
            created_at,
        }
    }
}

impl From<CreateExpenseDto> for Expense {
    fn from(dto: CreateExpenseDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            employee_id: dto.employee_id,
            category_id: dto.category_id,
            expense_date: dto.expense_date,
            description: dto.description,
            amount_total: dto.amount_total,
            currency: dto.currency,
            payment_mode: dto.payment_mode,
            reference: dto.reference,
            approval_state: dto.approval_state,
            state: dto.state,
            approval_request_id: dto.approval_request_id,
            journal_id: dto.journal_id,
            accounting_post_id: dto.accounting_post_id,
            reimbursement_id: dto.reimbursement_id,
            receipt_file_id: dto.receipt_file_id,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Expense> for ExpenseResponseDto {
    fn from(entity: &Expense) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            employee_id: entity.employee_id.clone(),
            category_id: entity.category_id.clone(),
            expense_date: entity.expense_date.clone(),
            description: entity.description.clone(),
            amount_total: entity.amount_total.clone(),
            currency: entity.currency.clone(),
            payment_mode: entity.payment_mode.clone(),
            reference: entity.reference.clone(),
            approval_state: entity.approval_state.clone(),
            state: entity.state.clone(),
            approval_request_id: entity.approval_request_id.clone(),
            journal_id: entity.journal_id.clone(),
            accounting_post_id: entity.accounting_post_id.clone(),
            reimbursement_id: entity.reimbursement_id.clone(),
            receipt_file_id: entity.receipt_file_id.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateExpenseDto> for Expense {
    fn from_create_dto(dto: CreateExpenseDto) -> backbone_core::ServiceResult<Self> {
        Ok(Expense::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateExpenseDto> for Expense {
    fn apply_update(mut self, dto: UpdateExpenseDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.employee_id = dto.employee_id;
        self.category_id = dto.category_id;
        self.expense_date = dto.expense_date;
        self.description = dto.description;
        self.amount_total = dto.amount_total;
        self.currency = dto.currency;
        self.payment_mode = dto.payment_mode;
        self.reference = dto.reference;
        self.approval_state = dto.approval_state;
        self.state = dto.state;
        self.approval_request_id = dto.approval_request_id;
        self.journal_id = dto.journal_id;
        self.accounting_post_id = dto.accounting_post_id;
        self.reimbursement_id = dto.reimbursement_id;
        self.receipt_file_id = dto.receipt_file_id;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Expense here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

