//! ExpenseTaxLine DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::ExpenseTaxLine;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new ExpenseTaxLine
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateExpenseTaxLineDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "expense_id")]
    pub expense_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub basis: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "account_id")]
    pub account_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub rate: Decimal,
    #[serde(alias = "tax_amount")]
    pub tax_amount: Decimal,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a ExpenseTaxLine
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateExpenseTaxLineDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "expense_id")]
    pub expense_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub basis: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "account_id")]
    pub account_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub rate: Decimal,
    #[serde(alias = "tax_amount")]
    pub tax_amount: Decimal,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a ExpenseTaxLine
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchExpenseTaxLineDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "expense_id")]
    pub expense_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub basis: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "account_id")]
    pub account_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rate: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "tax_amount")]
    pub tax_amount: Option<Decimal>,
}

impl PatchExpenseTaxLineDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.expense_id.is_some() || self.basis.is_some() || self.account_id.is_some() || self.description.is_some() || self.rate.is_some() || self.tax_amount.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for ExpenseTaxLine entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ExpenseTaxLineResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub expense_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub basis: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub account_id: Uuid,
    pub description: Option<String>,
    pub rate: Decimal,
    pub tax_amount: Decimal,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for ExpenseTaxLine entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ExpenseTaxLineListResponseDto {
    /// List of items
    pub items: Vec<ExpenseTaxLineResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl ExpenseTaxLineListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<ExpenseTaxLineResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ExpenseTaxLineSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub expense_id: Uuid,
    pub basis: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<ExpenseTaxLine> for ExpenseTaxLineResponseDto {
    fn from(entity: ExpenseTaxLine) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            expense_id: entity.expense_id,
            basis: entity.basis,
            account_id: entity.account_id,
            description: entity.description,
            rate: entity.rate,
            tax_amount: entity.tax_amount,
            metadata: entity.metadata,
        }
    }
}

impl From<ExpenseTaxLine> for ExpenseTaxLineSummaryDto {
    fn from(entity: ExpenseTaxLine) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            expense_id: entity.expense_id,
            basis: entity.basis,
            created_at,
        }
    }
}

impl From<CreateExpenseTaxLineDto> for ExpenseTaxLine {
    fn from(dto: CreateExpenseTaxLineDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            expense_id: dto.expense_id,
            basis: dto.basis,
            account_id: dto.account_id,
            description: dto.description,
            rate: dto.rate,
            tax_amount: dto.tax_amount,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&ExpenseTaxLine> for ExpenseTaxLineResponseDto {
    fn from(entity: &ExpenseTaxLine) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            expense_id: entity.expense_id.clone(),
            basis: entity.basis.clone(),
            account_id: entity.account_id.clone(),
            description: entity.description.clone(),
            rate: entity.rate.clone(),
            tax_amount: entity.tax_amount.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateExpenseTaxLineDto> for ExpenseTaxLine {
    fn from_create_dto(dto: CreateExpenseTaxLineDto) -> backbone_core::ServiceResult<Self> {
        Ok(ExpenseTaxLine::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateExpenseTaxLineDto> for ExpenseTaxLine {
    fn apply_update(mut self, dto: UpdateExpenseTaxLineDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.expense_id = dto.expense_id;
        self.basis = dto.basis;
        self.account_id = dto.account_id;
        self.description = dto.description;
        self.rate = dto.rate;
        self.tax_amount = dto.tax_amount;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to ExpenseTaxLine here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

