//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod expense_specification;
pub mod expense_category_specification;
pub mod expense_tax_line_specification;

// <<< CUSTOM
// END CUSTOM
