//! Application service for Expense entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `expense_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateExpenseDto, UpdateExpenseDto};
use crate::domain::entity::Expense;
use crate::infrastructure::persistence::ExpenseRepository;

/// Application service for Expense entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `expense_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ExpenseServiceCustom {
///     inner: Arc<ExpenseService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ExpenseService = GenericCrudService<
    Expense,
    CreateExpenseDto,
    UpdateExpenseDto,
    ExpenseRepository,
>;

// <<< CUSTOM
// END CUSTOM
