//! Application service for ExpenseCategory entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `expense_category_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateExpenseCategoryDto, UpdateExpenseCategoryDto};
use crate::domain::entity::ExpenseCategory;
use crate::infrastructure::persistence::ExpenseCategoryRepository;

/// Application service for ExpenseCategory entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `expense_category_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ExpenseCategoryServiceCustom {
///     inner: Arc<ExpenseCategoryService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ExpenseCategoryService = GenericCrudService<
    ExpenseCategory,
    CreateExpenseCategoryDto,
    UpdateExpenseCategoryDto,
    ExpenseCategoryRepository,
>;

// <<< CUSTOM
// END CUSTOM
