//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod expense_service;
pub mod expense_category_service;
pub mod expense_tax_line_service;

// <<< CUSTOM
// The validated write path (H-4) + its three seams: approvals (P6 engine), GL posting
// (shared backbone-gl-posting contract; sink wired by the app over accounting, W2), and
// reimbursement (adapter over payment's create_payment, W2). All default-unwired, fail-closed.
pub mod approvals_port;
pub mod expense_gl;
pub mod expenses_write_service;
pub mod reimbursement_port;
// END CUSTOM

pub use expense_service::ExpenseService;
pub use expense_category_service::ExpenseCategoryService;
pub use expense_tax_line_service::ExpenseTaxLineService;
// <<< CUSTOM
pub use approvals_port::{
    ApprovalFiling, ApprovalSeamError, ApprovalVerdict, ExpenseApprovalFilingRequest,
    UnwiredApprovals,
};
pub use expense_gl::{
    build_expense_envelope, PostAccounts, TaxLineInput, UnwiredGlSink, EnvelopeError,
    AccountingPostEnvelope, GlPostAck, GlPostLine, GlPostRejected, GlPostSink,
};
pub use expenses_write_service::{ExpenseWriteError, ExpensesWriteService, NewExpense};
pub use reimbursement_port::{
    ReimbursementAck, ReimbursementRequest, ReimbursementSeamError, ReimbursementSink,
    UnwiredReimbursement,
};
// END CUSTOM
