-- Expense Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the expenses.expenses table.
-- Customize this file to add your initial data.

-- INSERT INTO expenses.expenses (
--     id,
--     company_id,
--     employee_id,
--     category_id,
--     expense_date,
--     description,
--     amount_total,
--     currency,
--     payment_mode,
--     reference,
--     approval_state,
--     state,
--     approval_request_id,
--     journal_id,
--     accounting_post_id,
--     reimbursement_id,
--     receipt_file_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO expenses.expenses (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

