-- Company RLS fence for __module__ module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for expenses.expenses
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE expenses.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses.expenses FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS expenses_company_isolation ON expenses.expenses;
CREATE POLICY expenses_company_isolation ON expenses.expenses
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for expenses.expense_categories
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE expenses.expense_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses.expense_categories FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS expense_categories_company_isolation ON expenses.expense_categories;
CREATE POLICY expense_categories_company_isolation ON expenses.expense_categories
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for expenses.expense_tax_lines
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE expenses.expense_tax_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses.expense_tax_lines FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS expense_tax_lines_company_isolation ON expenses.expense_tax_lines;
CREATE POLICY expense_tax_lines_company_isolation ON expenses.expense_tax_lines
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

