-- Audit Triggers Migration for __module__ module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: Expense (expenses.expenses)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION expenses.expenses_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS expenses_insert_audit ON expenses.expenses;
CREATE TRIGGER expenses_insert_audit BEFORE INSERT ON expenses.expenses
    FOR EACH ROW EXECUTE FUNCTION expenses.expenses_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS expenses_update_audit ON expenses.expenses;
CREATE TRIGGER expenses_update_audit BEFORE UPDATE ON expenses.expenses
    FOR EACH ROW EXECUTE FUNCTION expenses.expenses_audit_timestamp();

-- ==============================================================================
-- Table: ExpenseCategory (expenses.expense_categories)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION expenses.expense_categories_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS expense_categories_insert_audit ON expenses.expense_categories;
CREATE TRIGGER expense_categories_insert_audit BEFORE INSERT ON expenses.expense_categories
    FOR EACH ROW EXECUTE FUNCTION expenses.expense_categories_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS expense_categories_update_audit ON expenses.expense_categories;
CREATE TRIGGER expense_categories_update_audit BEFORE UPDATE ON expenses.expense_categories
    FOR EACH ROW EXECUTE FUNCTION expenses.expense_categories_audit_timestamp();

-- ==============================================================================
-- Table: ExpenseTaxLine (expenses.expense_tax_lines)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION expenses.expense_tax_lines_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS expense_tax_lines_insert_audit ON expenses.expense_tax_lines;
CREATE TRIGGER expense_tax_lines_insert_audit BEFORE INSERT ON expenses.expense_tax_lines
    FOR EACH ROW EXECUTE FUNCTION expenses.expense_tax_lines_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS expense_tax_lines_update_audit ON expenses.expense_tax_lines;
CREATE TRIGGER expense_tax_lines_update_audit BEFORE UPDATE ON expenses.expense_tax_lines
    FOR EACH ROW EXECUTE FUNCTION expenses.expense_tax_lines_audit_timestamp();

