-- Migration: Create expenses table
-- Generated by metaphor-schema

-- Create expense_payment_mode enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'expense_payment_mode') THEN
        CREATE TYPE expense_payment_mode AS ENUM ('own_account', 'company_account');
    END IF;
END
$$;

-- Create expense_approval_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'expense_approval_state') THEN
        CREATE TYPE expense_approval_state AS ENUM ('draft', 'submitted', 'approved', 'refused');
    END IF;
END
$$;

-- Create expense_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'expense_state') THEN
        CREATE TYPE expense_state AS ENUM ('draft', 'submitted', 'approved', 'posted', 'done', 'refused');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS expenses;

CREATE TABLE IF NOT EXISTS expenses.expenses (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    employee_id UUID NOT NULL,
    category_id UUID NOT NULL,
    expense_date DATE NOT NULL,
    description TEXT NOT NULL,
    amount_total NUMERIC NOT NULL,
    currency TEXT NOT NULL DEFAULT 'IDR',
    payment_mode expense_payment_mode NOT NULL,
    reference TEXT,
    approval_state expense_approval_state NOT NULL,
    state expense_state NOT NULL,
    approval_request_id UUID,
    journal_id UUID,
    accounting_post_id UUID,
    reimbursement_id UUID,
    receipt_file_id UUID,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_expenses_company_id_employee_id_expense_date ON expenses.expenses (company_id, employee_id, expense_date);

CREATE INDEX IF NOT EXISTS idx_expenses_company_id_state ON expenses.expenses (company_id, state);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_expenses_metadata_gin ON expenses.expenses USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_expenses_metadata_deleted_at ON expenses.expenses ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_expenses_metadata_created_at ON expenses.expenses ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_expenses_metadata_updated_at ON expenses.expenses ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION expenses.expenses_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS expenses_insert_audit ON expenses.expenses;
CREATE TRIGGER expenses_insert_audit BEFORE INSERT ON expenses.expenses
    FOR EACH ROW EXECUTE FUNCTION expenses.expenses_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS expenses_update_audit ON expenses.expenses;
CREATE TRIGGER expenses_update_audit BEFORE UPDATE ON expenses.expenses
    FOR EACH ROW EXECUTE FUNCTION expenses.expenses_audit_timestamp();
