-- Enum types for __module__ module
-- Generated by metaphor-schema

-- Create expense_payment_mode enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'expense_payment_mode') THEN
        CREATE TYPE expense_payment_mode AS ENUM ('own_account', 'company_account');
    END IF;
END
$$;

-- Create expense_approval_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'expense_approval_state') THEN
        CREATE TYPE expense_approval_state AS ENUM ('draft', 'submitted', 'approved', 'refused');
    END IF;
END
$$;

-- Create expense_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'expense_state') THEN
        CREATE TYPE expense_state AS ENUM ('draft', 'submitted', 'approved', 'posted', 'done', 'refused');
    END IF;
END
$$;

