//! Domain events for ExpenseTaxLine entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::ExpenseTaxLine;

/// Domain events for ExpenseTaxLine — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ExpenseTaxLine>)` variant.
pub type ExpenseTaxLineEvent = CrudEvent<ExpenseTaxLine>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ExpenseTaxLine events.
pub type ExpenseTaxLineEventPublisher = Arc<dyn CrudEventPublisher<ExpenseTaxLine> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopExpenseTaxLineEventPublisher = NoOpCrudEventPublisher<ExpenseTaxLine>;
