//! Event handler trait for Expense events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ExpenseEvent;

/// Event handler for Expense events.
/// Implement this trait to react to Expense lifecycle events.
pub trait ExpenseEventHandler: EventHandler<ExpenseEvent> {}
