//! Domain events for ExpenseCategory entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::ExpenseCategory;

/// Domain events for ExpenseCategory — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ExpenseCategory>)` variant.
pub type ExpenseCategoryEvent = CrudEvent<ExpenseCategory>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ExpenseCategory events.
pub type ExpenseCategoryEventPublisher = Arc<dyn CrudEventPublisher<ExpenseCategory> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopExpenseCategoryEventPublisher = NoOpCrudEventPublisher<ExpenseCategory>;
