//! Event handler trait for ExpenseCategory events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ExpenseCategoryEvent;

/// Event handler for ExpenseCategory events.
/// Implement this trait to react to ExpenseCategory lifecycle events.
pub trait ExpenseCategoryEventHandler: EventHandler<ExpenseCategoryEvent> {}
