//! Domain events for Expense entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Expense;

/// Domain events for Expense — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Expense>)` variant.
pub type ExpenseEvent = CrudEvent<Expense>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Expense events.
pub type ExpenseEventPublisher = Arc<dyn CrudEventPublisher<Expense> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopExpenseEventPublisher = NoOpCrudEventPublisher<Expense>;
