//! Event handler trait for ExpenseTaxLine events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ExpenseTaxLineEvent;

/// Event handler for ExpenseTaxLine events.
/// Implement this trait to react to ExpenseTaxLine lifecycle events.
pub trait ExpenseTaxLineEventHandler: EventHandler<ExpenseTaxLineEvent> {}
