//! ExpenseTaxLine seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial ExpenseTaxLine data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// EXPENSETAXLINE SEEDER
// ============================================================================

/// Seeder for expense_tax_line
pub struct SeedExpenseTaxLineSeeder;

impl SeedExpenseTaxLineSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedExpenseTaxLineSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedExpenseTaxLineSeeder {
    fn name(&self) -> &'static str {
        "SeedExpenseTaxLineSeeder"
    }

    fn order(&self) -> i32 {
        3
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if expenses.expense_tax_lines table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM expenses.expense_tax_lines")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/expense_tax_line_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM expenses.expense_tax_lines")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

