//! Repository trait for Expense aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Expense aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Expense, ExpenseApprovalState, ExpensePaymentMode, ExpenseState};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ExpensePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ExpensePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ExpensePaginatedResult {
    pub data: Vec<Expense>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ExpenseFilter {
    pub company_id: Option<Uuid>,
    pub employee_id: Option<Uuid>,
    pub category_id: Option<Uuid>,
    pub description: Option<String>,
    pub currency: Option<String>,
    pub payment_mode: Option<ExpensePaymentMode>,
    pub reference: Option<String>,
    pub approval_state: Option<ExpenseApprovalState>,
    pub state: Option<ExpenseState>,
    pub approval_request_id: Option<Uuid>,
    pub journal_id: Option<Uuid>,
    pub accounting_post_id: Option<Uuid>,
    pub reimbursement_id: Option<Uuid>,
    pub receipt_file_id: Option<Uuid>,
}

impl ExpenseFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.category_id.is_some() || self.description.is_some() || self.currency.is_some() || self.payment_mode.is_some() || self.reference.is_some() || self.approval_state.is_some() || self.state.is_some() || self.approval_request_id.is_some() || self.journal_id.is_some() || self.accounting_post_id.is_some() || self.reimbursement_id.is_some() || self.receipt_file_id.is_some()
    }
}

/// Repository trait for Expense aggregate
///
/// This trait defines the persistence contract for Expense entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ExpenseRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new expense entity
    async fn save(&self, entity: &Expense) -> Result<Expense>;

    /// Find expense by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Expense>>;

    /// Find all expense entities
    async fn find_all(&self) -> Result<Vec<Expense>>;

    /// Update expense by ID
    async fn update(&self, id: &str, entity: &Expense) -> Result<Option<Expense>>;

    /// Delete expense by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List expense with pagination
    async fn list(&self, params: ExpensePaginationParams) -> Result<ExpensePaginatedResult>;

    /// List expense with pagination and filters
    async fn list_with_filters(&self, params: ExpensePaginationParams, filters: ExpenseFilter) -> Result<ExpensePaginatedResult>;

    /// Count all expense entities
    async fn count(&self) -> Result<u64>;

    /// Count expense entities matching filters
    async fn count_with_filters(&self, filters: ExpenseFilter) -> Result<u64>;

    /// Check if expense exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete expense by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted expense by ID
    async fn restore(&self, id: &str) -> Result<Option<Expense>>;

    /// List soft-deleted expense entities
    async fn list_deleted(&self, params: ExpensePaginationParams) -> Result<ExpensePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save expense entities
    async fn bulk_save(&self, entities: &[Expense]) -> Result<Vec<Expense>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
