//! Repository trait for ExpenseTaxLine aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ExpenseTaxLine aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::ExpenseTaxLine;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ExpenseTaxLinePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ExpenseTaxLinePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ExpenseTaxLinePaginatedResult {
    pub data: Vec<ExpenseTaxLine>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ExpenseTaxLineFilter {
    pub company_id: Option<Uuid>,
    pub expense_id: Option<Uuid>,
    pub basis: Option<String>,
    pub account_id: Option<Uuid>,
    pub description: Option<String>,
}

impl ExpenseTaxLineFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.expense_id.is_some() || self.basis.is_some() || self.account_id.is_some() || self.description.is_some()
    }
}

/// Repository trait for ExpenseTaxLine aggregate
///
/// This trait defines the persistence contract for ExpenseTaxLine entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ExpenseTaxLineRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new expense_tax_line entity
    async fn save(&self, entity: &ExpenseTaxLine) -> Result<ExpenseTaxLine>;

    /// Find expense_tax_line by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ExpenseTaxLine>>;

    /// Find all expense_tax_line entities
    async fn find_all(&self) -> Result<Vec<ExpenseTaxLine>>;

    /// Update expense_tax_line by ID
    async fn update(&self, id: &str, entity: &ExpenseTaxLine) -> Result<Option<ExpenseTaxLine>>;

    /// Delete expense_tax_line by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List expense_tax_line with pagination
    async fn list(&self, params: ExpenseTaxLinePaginationParams) -> Result<ExpenseTaxLinePaginatedResult>;

    /// List expense_tax_line with pagination and filters
    async fn list_with_filters(&self, params: ExpenseTaxLinePaginationParams, filters: ExpenseTaxLineFilter) -> Result<ExpenseTaxLinePaginatedResult>;

    /// Count all expense_tax_line entities
    async fn count(&self) -> Result<u64>;

    /// Count expense_tax_line entities matching filters
    async fn count_with_filters(&self, filters: ExpenseTaxLineFilter) -> Result<u64>;

    /// Check if expense_tax_line exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete expense_tax_line by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted expense_tax_line by ID
    async fn restore(&self, id: &str) -> Result<Option<ExpenseTaxLine>>;

    /// List soft-deleted expense_tax_line entities
    async fn list_deleted(&self, params: ExpenseTaxLinePaginationParams) -> Result<ExpenseTaxLinePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save expense_tax_line entities
    async fn bulk_save(&self, entities: &[ExpenseTaxLine]) -> Result<Vec<ExpenseTaxLine>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
