//! Repository trait for ExpenseCategory aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ExpenseCategory aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::ExpenseCategory;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ExpenseCategoryPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ExpenseCategoryPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ExpenseCategoryPaginatedResult {
    pub data: Vec<ExpenseCategory>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ExpenseCategoryFilter {
    pub company_id: Option<Uuid>,
    pub code: Option<String>,
    pub name: Option<String>,
    pub expense_account_id: Option<Uuid>,
    pub description: Option<String>,
}

impl ExpenseCategoryFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.code.is_some() || self.name.is_some() || self.expense_account_id.is_some() || self.description.is_some()
    }
}

/// Repository trait for ExpenseCategory aggregate
///
/// This trait defines the persistence contract for ExpenseCategory entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ExpenseCategoryRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new expense_category entity
    async fn save(&self, entity: &ExpenseCategory) -> Result<ExpenseCategory>;

    /// Find expense_category by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ExpenseCategory>>;

    /// Find all expense_category entities
    async fn find_all(&self) -> Result<Vec<ExpenseCategory>>;

    /// Update expense_category by ID
    async fn update(&self, id: &str, entity: &ExpenseCategory) -> Result<Option<ExpenseCategory>>;

    /// Delete expense_category by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List expense_category with pagination
    async fn list(&self, params: ExpenseCategoryPaginationParams) -> Result<ExpenseCategoryPaginatedResult>;

    /// List expense_category with pagination and filters
    async fn list_with_filters(&self, params: ExpenseCategoryPaginationParams, filters: ExpenseCategoryFilter) -> Result<ExpenseCategoryPaginatedResult>;

    /// Count all expense_category entities
    async fn count(&self) -> Result<u64>;

    /// Count expense_category entities matching filters
    async fn count_with_filters(&self, filters: ExpenseCategoryFilter) -> Result<u64>;

    /// Check if expense_category exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete expense_category by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted expense_category by ID
    async fn restore(&self, id: &str) -> Result<Option<ExpenseCategory>>;

    /// List soft-deleted expense_category entities
    async fn list_deleted(&self, params: ExpenseCategoryPaginationParams) -> Result<ExpenseCategoryPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save expense_category entities
    async fn bulk_save(&self, entities: &[ExpenseCategory]) -> Result<Vec<ExpenseCategory>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
