//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod expense_repository;
pub mod expense_category_repository;
pub mod expense_tax_line_repository;

// Re-exports
pub use expense_repository::{
    ExpenseRepository,
    ExpensePaginationParams,
    ExpensePaginatedResult,
    ExpenseFilter,
};
pub use expense_category_repository::{
    ExpenseCategoryRepository,
    ExpenseCategoryPaginationParams,
    ExpenseCategoryPaginatedResult,
    ExpenseCategoryFilter,
};
pub use expense_tax_line_repository::{
    ExpenseTaxLineRepository,
    ExpenseTaxLinePaginationParams,
    ExpenseTaxLinePaginatedResult,
    ExpenseTaxLineFilter,
};
