//! Repository for ExpenseTaxLine entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ExpenseTaxLine, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::ExpenseTaxLine;

/// Table name for ExpenseTaxLine entities
pub const TABLE_NAME: &str = "expenses.expense_tax_lines";

/// Repository for ExpenseTaxLine entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ExpenseTaxLineRepository(
    backbone_orm::GenericCrudRepository<ExpenseTaxLine, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ExpenseTaxLineRepository {
    type Target = backbone_orm::GenericCrudRepository<ExpenseTaxLine, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ExpenseTaxLineRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(ExpenseTaxLineRepository, ExpenseTaxLine, soft_delete);
