//! Repository for ExpenseCategory entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ExpenseCategory, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::ExpenseCategory;

/// Table name for ExpenseCategory entities
pub const TABLE_NAME: &str = "expenses.expense_categories";

/// Repository for ExpenseCategory entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ExpenseCategoryRepository(
    backbone_orm::GenericCrudRepository<ExpenseCategory, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ExpenseCategoryRepository {
    type Target = backbone_orm::GenericCrudRepository<ExpenseCategory, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ExpenseCategoryRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(ExpenseCategoryRepository, ExpenseCategory, soft_delete);
