//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod expense_repository;
mod expense_category_repository;
mod expense_tax_line_repository;

// Custom persistence modules
// <<< CUSTOM
// Hand-written repository: every SQL statement of the validated write path (H-4).
pub mod expenses_write_repository;
// END CUSTOM

// Re-exports
pub use expense_repository::ExpenseRepository;
pub use expense_category_repository::ExpenseCategoryRepository;
pub use expense_tax_line_repository::ExpenseTaxLineRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
pub use expenses_write_repository::{
    ExpensePatch, ExpenseReportRow, ExpensesWriteRepository, TaxLineWrite,
};
// END CUSTOM
