//! Validator for ExpenseTaxLine entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<ExpenseTaxLine>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::ExpenseTaxLine;

/// Validator type alias for ExpenseTaxLine entities.
pub type ExpenseTaxLineValidator = EntityValidator<ExpenseTaxLine>;

/// Build a validator for ExpenseTaxLine with all schema-defined field rules.
pub fn expense_tax_line_validator() -> ExpenseTaxLineValidator {
    EntityValidator::new()
        .rule(RequiredString::new("basis", |e: &ExpenseTaxLine| &e.basis))
        .rule(OptionalNotBlank::new("description", |e: &ExpenseTaxLine| e.description.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
