//! Validator for Expense entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Expense>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::Expense;

/// Validator type alias for Expense entities.
pub type ExpenseValidator = EntityValidator<Expense>;

/// Build a validator for Expense with all schema-defined field rules.
pub fn expense_validator() -> ExpenseValidator {
    EntityValidator::new()
        .rule(RequiredString::new("description", |e: &Expense| &e.description))
        .rule(RequiredString::new("currency", |e: &Expense| &e.currency))
        .rule(OptionalNotBlank::new("reference", |e: &Expense| e.reference.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
