//! Validator for ExpenseCategory entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<ExpenseCategory>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::ExpenseCategory;

/// Validator type alias for ExpenseCategory entities.
pub type ExpenseCategoryValidator = EntityValidator<ExpenseCategory>;

/// Build a validator for ExpenseCategory with all schema-defined field rules.
pub fn expense_category_validator() -> ExpenseCategoryValidator {
    EntityValidator::new()
        .rule(RequiredString::new("code", |e: &ExpenseCategory| &e.code))
        .rule(RequiredString::new("name", |e: &ExpenseCategory| &e.name))
        .rule(OptionalNotBlank::new("description", |e: &ExpenseCategory| e.description.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
