//! Expense API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Expense CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// EXPENSE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Expense
pub struct ExpenseTestData;

impl TestDataGenerator for ExpenseTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "category_id": Uuid::new_v4().to_string(),
            "expense_date": Utc::now().format("%Y-%m-%d").to_string(),
            "description": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "amount_total": 0,
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "payment_mode": "own_account",
            "reference": null,
            "approval_state": "draft",
            "state": "draft",
            "approval_request_id": null,
            "journal_id": null,
            "accounting_post_id": null,
            "reimbursement_id": null,
            "receipt_file_id": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "category_id": Uuid::new_v4().to_string(),
            "expense_date": Utc::now().format("%Y-%m-%d").to_string(),
            "description": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "amount_total": 0,
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "payment_mode": "own_account",
            "reference": null,
            "approval_state": "draft",
            "state": "draft",
            "approval_request_id": null,
            "journal_id": null,
            "accounting_post_id": null,
            "reimbursement_id": null,
            "receipt_file_id": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// EXPENSE API TEST
// ============================================================================

/// Expense API test suite
pub struct ExpenseApiTest {
    inner: GenericCrudTest<ExpenseTestData>,
}

impl ExpenseApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/expenses", "Expense");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, ExpenseTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for ExpenseApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_expense_crud() {
        let mut test = ExpenseApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Expense specific tests here
// <<< CUSTOM TESTS END >>>
