//! ExpenseTaxLine API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the ExpenseTaxLine CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// EXPENSETAXLINE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for ExpenseTaxLine
pub struct ExpenseTaxLineTestData;

impl TestDataGenerator for ExpenseTaxLineTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "expense_id": Uuid::new_v4().to_string(),
            "basis": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "account_id": Uuid::new_v4().to_string(),
            "description": null,
            "rate": 0,
            "tax_amount": 0,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "expense_id": Uuid::new_v4().to_string(),
            "basis": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "account_id": Uuid::new_v4().to_string(),
            "description": null,
            "rate": 0,
            "tax_amount": 0,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// EXPENSETAXLINE API TEST
// ============================================================================

/// ExpenseTaxLine API test suite
pub struct ExpenseTaxLineApiTest {
    inner: GenericCrudTest<ExpenseTaxLineTestData>,
}

impl ExpenseTaxLineApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/expense_tax_lines", "ExpenseTaxLine");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, ExpenseTaxLineTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for ExpenseTaxLineApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_expense_tax_line_crud() {
        let mut test = ExpenseTaxLineApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add ExpenseTaxLine specific tests here
// <<< CUSTOM TESTS END >>>
