//! Integration Test Implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Contains CRUD API tests for all entities.

pub mod crud_test_base;

pub mod expense_api_test;
pub mod expense_category_api_test;
pub mod expense_tax_line_api_test;

// Re-exports for convenience
pub use crud_test_base::*;
pub use expense_api_test::*;
pub use expense_category_api_test::*;
pub use expense_tax_line_api_test::*;
