//! Expenses Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::ExpenseService;
use crate::application::service::ExpenseCategoryService;
use crate::application::service::ExpenseTaxLineService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// Expense service
    pub expense_service: Arc<ExpenseService>,
    /// ExpenseCategory service
    pub expense_category_service: Arc<ExpenseCategoryService>,
    /// ExpenseTaxLine service
    pub expense_tax_line_service: Arc<ExpenseTaxLineService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        expense_service: Arc<ExpenseService>,
        expense_category_service: Arc<ExpenseCategoryService>,
        expense_tax_line_service: Arc<ExpenseTaxLineService>
    ) -> Self {
        Self {
            expense_service,
            expense_category_service,
            expense_tax_line_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::ExpensesModule) -> Self {
        Self {
            expense_service: module.expense_service.clone(),
            expense_category_service: module.expense_category_service.clone(),
            expense_tax_line_service: module.expense_tax_line_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    expense_service: Option<Arc<ExpenseService>>,
    expense_category_service: Option<Arc<ExpenseCategoryService>>,
    expense_tax_line_service: Option<Arc<ExpenseTaxLineService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the Expense service.
    pub fn with_expense_service(mut self, service: Arc<ExpenseService>) -> Self {
        self.expense_service = Some(service);
        self
    }

    /// Set the ExpenseCategory service.
    pub fn with_expense_category_service(mut self, service: Arc<ExpenseCategoryService>) -> Self {
        self.expense_category_service = Some(service);
        self
    }

    /// Set the ExpenseTaxLine service.
    pub fn with_expense_tax_line_service(mut self, service: Arc<ExpenseTaxLineService>) -> Self {
        self.expense_tax_line_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            expense_service: self.expense_service.expect("expense_service is required"),
            expense_category_service: self.expense_category_service.expect("expense_category_service is required"),
            expense_tax_line_service: self.expense_tax_line_service.expect("expense_tax_line_service is required"),
        }
    }
}
