//! Public events for Expenses module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// EXPENSE EVENTS
// ============================================================================

/// Event published when a Expense is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExpenseCreatedEvent {
    pub id: ExpenseId,
    pub data: ExpenseDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Expense is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExpenseUpdatedEvent {
    pub id: ExpenseId,
    pub data: ExpenseDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Expense is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExpenseDeletedEvent {
    pub id: ExpenseId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// EXPENSECATEGORY EVENTS
// ============================================================================

/// Event published when a ExpenseCategory is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExpenseCategoryCreatedEvent {
    pub id: ExpenseCategoryId,
    pub data: ExpenseCategoryDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ExpenseCategory is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExpenseCategoryUpdatedEvent {
    pub id: ExpenseCategoryId,
    pub data: ExpenseCategoryDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ExpenseCategory is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExpenseCategoryDeletedEvent {
    pub id: ExpenseCategoryId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// EXPENSETAXLINE EVENTS
// ============================================================================

/// Event published when a ExpenseTaxLine is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExpenseTaxLineCreatedEvent {
    pub id: ExpenseTaxLineId,
    pub data: ExpenseTaxLineDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ExpenseTaxLine is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExpenseTaxLineUpdatedEvent {
    pub id: ExpenseTaxLineId,
    pub data: ExpenseTaxLineDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ExpenseTaxLine is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExpenseTaxLineDeletedEvent {
    pub id: ExpenseTaxLineId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// Expenses EVENT ENUM
// ============================================================================

/// All events published by Expenses module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ExpensesEvent {
    ExpenseCreated(ExpenseCreatedEvent),
    ExpenseUpdated(ExpenseUpdatedEvent),
    ExpenseDeleted(ExpenseDeletedEvent),
    ExpenseCategoryCreated(ExpenseCategoryCreatedEvent),
    ExpenseCategoryUpdated(ExpenseCategoryUpdatedEvent),
    ExpenseCategoryDeleted(ExpenseCategoryDeletedEvent),
    ExpenseTaxLineCreated(ExpenseTaxLineCreatedEvent),
    ExpenseTaxLineUpdated(ExpenseTaxLineUpdatedEvent),
    ExpenseTaxLineDeleted(ExpenseTaxLineDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExpensesEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for ExpensesEventMetadata {
    fn default() -> Self {
        Self {
            module: "__Expenses__",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
