//! Expenses Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Expenses exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use __Expenses__::exports::{ExpenseDto};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `ExpenseDto` - Data transfer object for Expense
/// - `ExpenseSummary` - Summary view of Expense
/// - `ExpenseId` - Type-safe ID wrapper
/// - `ExpenseCategoryDto` - Data transfer object for ExpenseCategory
/// - `ExpenseCategorySummary` - Summary view of ExpenseCategory
/// - `ExpenseCategoryId` - Type-safe ID wrapper
/// - `ExpenseTaxLineDto` - Data transfer object for ExpenseTaxLine
/// - `ExpenseTaxLineSummary` - Summary view of ExpenseTaxLine
/// - `ExpenseTaxLineId` - Type-safe ID wrapper
///
/// ## Public Events
/// - `ExpenseCreatedEvent` - Published when Expense is created
/// - `ExpenseUpdatedEvent` - Published when Expense is updated
/// - `ExpenseDeletedEvent` - Published when Expense is deleted
/// - `ExpenseCategoryCreatedEvent` - Published when ExpenseCategory is created
/// - `ExpenseCategoryUpdatedEvent` - Published when ExpenseCategory is updated
/// - `ExpenseCategoryDeletedEvent` - Published when ExpenseCategory is deleted
/// - `ExpenseTaxLineCreatedEvent` - Published when ExpenseTaxLine is created
/// - `ExpenseTaxLineUpdatedEvent` - Published when ExpenseTaxLine is updated
/// - `ExpenseTaxLineDeletedEvent` - Published when ExpenseTaxLine is deleted
pub struct ExportSummary;
