//! Expenses Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;
pub mod exports;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::ExpenseService;
pub use application::service::ExpenseCategoryService;
pub use application::service::ExpenseTaxLineService;

// <<< CUSTOM
// The validated write path (H-4), its seam ports (approvals / GL / reimbursement — all
// default-unwired, fail-closed), the guarded HTTP composition, and `company_scope` re-exported
// for the RLS probe suite (tests see only the public surface — party/attendance convention).
pub use application::service::{
    build_expense_envelope, AccountingPostEnvelope, ApprovalFiling, ApprovalSeamError,
    ApprovalVerdict, EnvelopeError, ExpenseApprovalFilingRequest, ExpenseWriteError,
    ExpensesWriteService, GlPostAck, GlPostLine, GlPostRejected, GlPostSink, NewExpense,
    PostAccounts, ReimbursementAck, ReimbursementRequest, ReimbursementSeamError,
    ReimbursementSink, TaxLineInput, UnwiredApprovals, UnwiredGlSink, UnwiredReimbursement,
};
pub use presentation::http::create_guarded_expenses_routes;
pub use backbone_orm::company_scope;
// END CUSTOM

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Expenses module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let expenses = ExpensesModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = expenses.all_crud_routes();
/// ```
pub struct ExpensesModule {
    pub(crate) expense_service: Arc<ExpenseService>,
    pub(crate) expense_category_service: Arc<ExpenseCategoryService>,
    pub(crate) expense_tax_line_service: Arc<ExpenseTaxLineService>,
    // <<< CUSTOM FIELDS
    // The validated claim verbs (create/update/submit/approve/refuse/post/settle, tax overlay,
    // receipts) and their three seam ports.
    pub(crate) expenses_write_service: Arc<ExpensesWriteService>,
    // END CUSTOM
}

impl ExpensesModule {
    /// Create a new module builder
    pub fn builder() -> ExpensesModuleBuilder {
        ExpensesModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_expense_routes,
            create_expense_category_routes,
            create_expense_tax_line_routes,
        };

        Router::new()
            .merge(create_expense_routes(self.expense_service.clone()))
            .merge(create_expense_category_routes(self.expense_category_service.clone()))
            .merge(create_expense_tax_line_routes(self.expense_tax_line_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD; prefer readonly_routes() + validated writes, or all_crud_routes() for the full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }

    /// Read-only routes for every entity (GET endpoints only) — the safe base.
    ///
    /// Generic mutation can't reach here, so this surface cannot bypass a
    /// validated write service's invariants. Use this as the production base and
    /// merge validated write routes (or a write service's HTTP layer) onto it.
    pub fn readonly_routes(&self) -> Router {
        use presentation::http::{
            create_expense_read_routes,
            create_expense_category_read_routes,
            create_expense_tax_line_read_routes,
        };

        Router::new()
            .merge(create_expense_read_routes(self.expense_service.clone()))
            .merge(create_expense_category_read_routes(self.expense_category_service.clone()))
            .merge(create_expense_tax_line_read_routes(self.expense_tax_line_service.clone()))
    }

    // <<< CUSTOM METHODS
    /// The validated write path (seams default-unwired). Composition points that need to wire
    /// the approvals/GL/reimbursement ports build their own from the same pool:
    /// `ExpensesWriteService::new(pool).with_gl_sink(sink).with_approvals(port)`.
    pub fn expenses_write_service(&self) -> Arc<ExpensesWriteService> {
        self.expenses_write_service.clone()
    }

    /// Arm the approvals seam on the module-built service after the fact (last writer wins;
    /// callers arm exactly once at composition time).
    pub fn set_expenses_approvals(&self, port: Arc<dyn ApprovalFiling>) {
        self.expenses_write_service.set_approvals(port);
    }

    /// Replace the write service at the composition root — how a host swaps in a service built
    /// with real adapters over the fail-closed seams (GL posting, reimbursement) or its own
    /// approvals port. Consuming `self` keeps the chain reading naturally; call before mounting
    /// routes, the module is consumed once at startup.
    pub fn with_expenses_write_service(mut self, svc: Arc<ExpensesWriteService>) -> Self {
        self.expenses_write_service = svc;
        self
    }
    // END CUSTOM
}

/// Builder for ExpensesModule
pub struct ExpensesModuleBuilder {
    db_pool: Option<PgPool>,
}

impl ExpensesModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<ExpensesModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // Expense service
        let expense_repository = Arc::new(ExpenseRepository::new(db_pool.clone()));
        let expense_service = Arc::new(ExpenseService::with_repository(expense_repository.clone()));

        // ExpenseCategory service
        let expense_category_repository = Arc::new(ExpenseCategoryRepository::new(db_pool.clone()));
        let expense_category_service = Arc::new(ExpenseCategoryService::with_repository(expense_category_repository.clone()));

        // ExpenseTaxLine service
        let expense_tax_line_repository = Arc::new(ExpenseTaxLineRepository::new(db_pool.clone()));
        let expense_tax_line_service = Arc::new(ExpenseTaxLineService::with_repository(expense_tax_line_repository.clone()));

        // <<< CUSTOM
        // The validated write path (H-4): verbs + seams, all default-unwired (approve is
        // TR2-fail-closed, post/settle fail closed until W2/P6 wire the adapters).
        let expenses_write_service = Arc::new(ExpensesWriteService::new(db_pool.clone()));
        // END CUSTOM

        Ok(ExpensesModule {
            expense_service,
            expense_category_service,
            expense_tax_line_service,
            // <<< CUSTOM
            expenses_write_service,
            // END CUSTOM
        })
    }
}

impl Default for ExpensesModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
