//! HTTP handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod expense_handler;
pub mod expense_category_handler;
pub mod expense_tax_line_handler;

// <<< CUSTOM
// The guarded composition (validated claim verbs + report projection + category CRUD +
// safe reads) — the RECOMMENDED mount for production hosts.
pub mod guarded_routes;
// END CUSTOM

// Re-exports
pub use expense_handler::{create_expense_routes, create_expense_read_routes, create_expense_write_routes};
pub use expense_category_handler::{create_expense_category_routes, create_expense_category_read_routes, create_expense_category_write_routes};
pub use expense_tax_line_handler::{create_expense_tax_line_routes, create_expense_tax_line_read_routes, create_expense_tax_line_write_routes};
// <<< CUSTOM
pub use guarded_routes::create_guarded_expenses_routes;
// END CUSTOM
